theme: jekyll-theme-slate
title: Mariana S. C. Almeida
description:  [**News**](#news)  &nbsp;  [**Degrees**](#degrees)  &nbsp; [**Awards**](#awards) &nbsp; [**Publications**](#publications) &nbsp; [**Contacts**](#contacts)

